In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_excel(r"C:\Users\sanju\HR_Employee_Attrition_Analysis_Project.xlsx")

In [4]:
print(df.shape)

(1480, 38)

In [5]:
df.head()

,EmpID,Age,AgeGroup,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,RM297,18,18-25,Yes,Travel_Rarely,230,Research & Development,3,3,Life Sciences,...,3,80,0,0,2,3,0,0,0,0
1,RM302,18,18-25,No,Travel_Rarely,812,Sales,10,3,Medical,...,1,80,0,0,2,3,0,0,0,0
2,RM458,18,18-25,Yes,Travel_Frequently,1306,Sales,5,3,Marketing,...,4,80,0,0,3,3,0,0,0,0
3,RM728,18,18-25,No,Non-Travel,287,Research & Development,5,2,Life Sciences,...,4,80,0,0,2,3,0,0,0,0
4,RM829,18,18-25,Yes,Non-Travel,247,Research & Development,8,1,Medical,...,4,80,0,0,0,3,0,0,0,0

In [6]:
df.columns

Index(['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate',
       'Department', 'DistanceFromHome', 'Education', 'EducationField',
       'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender',
       'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole',
       'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'SalarySlab',
       'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'StockOptionLevel', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany',
       'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [7]:
df.dtypes

EmpID                       object
Age                          int64
AgeGroup                    object
Attrition                   object
BusinessTravel              object
DailyRate                    int64
Department                  object
DistanceFromHome             int64
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
HourlyRate                   int64
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
SalarySlab                  object
MonthlyRate                  int64
NumCompaniesWorked           int64
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
StockOptionLevel             int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
YearsWithCurrManager         int64
dtype: object

In [9]:
print("Hello")

Hello

In [10]:
df.isnull().sum()

EmpID                       0
Age                         0
AgeGroup                    0
Attrition                   0
BusinessTravel              0
DailyRate                   0
Department                  0
DistanceFromHome            0
Education                   0
EducationField              0
EmployeeCount               0
EmployeeNumber              0
EnvironmentSatisfaction     0
Gender                      0
HourlyRate                  0
JobInvolvement              0
JobLevel                    0
JobRole                     0
JobSatisfaction             0
MaritalStatus               0
MonthlyIncome               0
SalarySlab                  0
MonthlyRate                 0
NumCompaniesWorked          0
Over18                      0
OverTime                    0
PercentSalaryHike           0
PerformanceRating           0
RelationshipSatisfaction    0
StandardHours               0
StockOptionLevel            0
TotalWorkingYears           0
TrainingTimesLastYear       0
WorkLifeBalance             0
YearsAtCompany              0
YearsInCurrentRole          0
YearsSinceLastPromotion     0
YearsWithCurrManager        0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(7)

In [12]:
df["Attrition"].value_counts()

Attrition
No     1242
Yes     238
Name: count, dtype: int64

In [13]:
(df["Attrition"].value_counts(normalize=True)*100).round(2)

Attrition
No     83.92
Yes    16.08
Name: proportion, dtype: float64

In [15]:
print(df.columns.tolist())

['EmpID', 'Age', 'AgeGroup', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department', 'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount', 'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate', 'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome', 'SalarySlab', 'MonthlyRate', 'NumCompaniesWorked', 'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion', 'YearsWithCurrManager']

In [17]:
df.columns =df.columns.str.strip()

In [18]:
pd.crosstab(df["Department"],df["Attrition"])

Attrition                No  Yes
Department
Human Resources          51   12
Research & Development  834  133
Sales                   357   93

In [20]:
pd.crosstab(df["JobRole"],df["Attrition"])

Attrition                   No  Yes
JobRole
Healthcare Representative  123    9
Human Resources             40   12
Laboratory Technician      199   62
Manager                     97    5
Manufacturing Director     137   10
Research Director           78    2
Research Scientist         246   47
Sales Executive            271   58
Sales Representative        51   33

In [21]:
pd.crosstab(df["OverTime"],df["Attrition"])

Attrition   No  Yes
OverTime
No         952  110
Yes        290  128

In [22]:
pd.crosstab(df["AgeGroup"],df["Attrition"])

Attrition   No  Yes
AgeGroup
18-25       79   44
26-35      495  116
36-45      428   43
46-55      201   27
55+         39    8

In [23]:
pd.crosstab(df["JobSatisfaction"],df["Attrition"])

Attrition         No  Yes
JobSatisfaction
1                226   67
2                236   46
3                371   73
4                409   52

In [25]:
pd.crosstab(df["WorkLifeBalance"],df["Attrition"])

Attrition         No  Yes
WorkLifeBalance
1                 56   25
2                288   58
3                771  128
4                127   27

In [26]:
df.groupby("Attrition")["MonthlyIncome"].mean().round(2)

Attrition
No     6829.29
Yes    4812.58
Name: MonthlyIncome, dtype: float64

In [27]:
pd.crosstab(df["Department"],df["Attrition"],normalize="index").mul(100).round(2)

Attrition                  No    Yes
Department
Human Resources         80.95  19.05
Research & Development  86.25  13.75
Sales                   79.33  20.67

In [28]:
pd.crosstab(df["OverTime"],df["Attrition"],normalize="index").mul(100).round(2)

Attrition     No    Yes
OverTime
No         89.64  10.36
Yes        69.38  30.62

In [30]:
pd.crosstab(df["AgeGroup"],df["Attrition"],normalize="index").mul(100).round(2)

Attrition     No    Yes
AgeGroup
18-25      64.23  35.77
26-35      81.01  18.99
36-45      90.87   9.13
46-55      88.16  11.84
55+        82.98  17.02

In [31]:
df.groupby("JobRole")["MonthlyIncome"].mean().round(2)

JobRole
Healthcare Representative     7547.42
Human Resources               4235.75
Laboratory Technician         3239.09
Manager                      17181.68
Manufacturing Director        7305.26
Research Director            16033.55
Research Scientist            3241.83
Sales Executive               6947.08
Sales Representative          2630.05
Name: MonthlyIncome, dtype: float64

In [33]:
df.groupby("Attrition")["YearsAtCompany"].mean().round(2)

Attrition
No     7.37
Yes    5.12
Name: YearsAtCompany, dtype: float64

In [34]:
pd.crosstab(df["JobSatisfaction"],df["Attrition"],normalize="index").mul(100).round(2)

Attrition           No    Yes
JobSatisfaction
1                77.13  22.87
2                83.69  16.31
3                83.56  16.44
4                88.72  11.28

In [35]:
df.to_csv("HR_Employee_Attrition_Cleaned.csv",index=False)

In [36]:
import os
os.path.exists("HR_Employee_Attrition_Cleaned.csv")

True